# Generated by Django 2.0.2 on 2018-03-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=100)),
                ('username', models.CharField(default='guest', max_length=100)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('url', models.CharField(max_length=10000)),
            ],
        ),
    ]
