# Generated by Django 2.0.2 on 2018-04-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productdb', '0002_auto_20180322_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
