# Generated by Django 2.0.2 on 2018-04-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='guest', max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('mono', models.CharField(max_length=10)),
            ],
        ),
    ]
