# Generated by Django 2.0.2 on 2018-03-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='guest', max_length=100)),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
                ('area', models.CharField(default='SOME STRING', max_length=100)),
                ('buldingname', models.CharField(default='SOME STRING', max_length=100)),
                ('landmark', models.CharField(default='SOME STRING', max_length=100)),
                ('mobileno', models.IntegerField(default=0)),
                ('productid', models.CharField(default='SOME STRING', max_length=100)),
                ('ddate', models.DateField(blank=True)),
                ('city', models.CharField(default='SOME STRING', max_length=100)),
                ('state', models.CharField(default='SOME STRING', max_length=100)),
                ('pincode', models.IntegerField(default=0)),
                ('ordertime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
