# Generated by Django 2.0.2 on 2018-03-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobileno',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.CharField(max_length=7),
        ),
    ]
