# Generated by Django 2.0.2 on 2018-03-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tprice',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
