# Generated by Django 2.0.2 on 2018-03-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartdb', '0002_cart_tprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='tprice',
        ),
    ]
